services:
  db:
    build: .
    image: english_words_learning_bot_postgres_image
    restart: always
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./01_run_generate_data_script.sh:/docker-entrypoint-initdb.d/02_run_generate_data_script.sh
      - ./data.sql:/docker-entrypoint-initdb.d/03_data.sql
      - ./generate_data.py:/docker-entrypoint-initdb.d/04_generate_data.py
      - ./words.json:/docker-entrypoint-initdb.d/05_words.json
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
